language: c
sudo: required
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libtommath-dev
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libtommath-dev
            - clang-3.9
    - os: osx
      image: xcode8
notifications:
  email: false
before_install:
  - if [ "$(uname)" = "Darwin" ]; then
      brew update;
      brew install -v libtommath concurrencykit;
    fi
  - if [ "$(uname)" = "Linux" ]; then
      git clone https://github.com/concurrencykit/ck.git ${HOME}/ck --branch 0.6.0 --depth 1;
      cd ${HOME}/ck;
      ./configure;
      make all;
      sudo make install;
    fi
script:
  - make
  - sudo make install
  - make test
